export const AMPLIFY_AUTH_REGION = process.env.REACT_APP_AMPLIFY_AUTH_REGION;
export const AMPLIFY_AUTH_USER_POOL_CLIENT_ID = process.env.REACT_APP_AMPLIFY_AUTH_USER_POOL_CLIENT_ID;
export const AMPLIFY_AUTH_USER_POOL_ID = process.env.REACT_APP_AMPLIFY_AUTH_USER_POOL_ID; 
export const AMPLIFY_AUTH_USER_POOL_CLIENT_SECRET = process.env.REACT_APP_AMPLIFY_AUTH_USER_POOL_CLIENT_SECRET;
export const API_BASE_URL = process.env.REACT_APP_API_BASE_URL;